/** @param {NS} ns */
export async function main(ns) {

	const dndlogo = [
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0OkxxxxkO0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNMWX0kdolcc:::::::clodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOdd00xl:;;;;;;;;;;;;;;;;;;:cokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o:;cl:;;;;;;;;;;;;;;;;;;;;;;;;:cd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMXd:;;;;;;;;;;;;;;;:::::;;;;;;;;;;;;;;;:lOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMNXNXx:;;;;;;;;;;;;:ldk0KKK0kdl:;;;;;;;;;;;;;cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMNkdOkc;;;;;;;;;;;:lkXWMMMMMMMWXkl:;;;;;;;;;;;;l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMW0c:lc;;;;;;;;;;;:oKWMMMMMMMMMMMW0l;;;;;;;;;;;;:dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMNd:;;;;;;;;;;;;;;lKWMMMMMMMMMMMMMWOc;;;;;;;;;;;;cOWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMKo;;;;;;;;;;;;;;:dNMMMMMMMMMMMMMMWKo;;;;;;;;;;;;:xXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMWKo;;;;;:;;;;;;;;:dXWXNMMMMMWWMMMMWKo;;;;;;;;;;;;:xXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMXo;;;;lxl;;;;;;;;oKKdkWMMMN0KWMMMW0l;;;;;;;;;;;;:kXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMNx:;;cONOl;;;;;;:xKx:oKWMM0oxNMMMNx:;;;;;;;;;;;;l0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMW0l;;oKNXOl:;;;;cOKo;:dXWWOccONWNkc;;;;;;;;;;;;:xNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMWkc:xKkd0Kxc;;;l00l;;:o0NOc;ckNKo:;;;;;;;;;;;;lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMNOlxKd:lx00xl:l00l;;;;cxOxc::dO0dc;;;;;;;;;;cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMWK0XOc;:cdk0OkKKo;;;;;:cdxdl:cxOOdc:;;;;;;cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMWXOkxkkkkl:;;;:ldkKX0dc;;;;;;cdkxl:cxOOxc:;;;lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMWXkl:;;::;;;;;;;;coxOOdc:;;;;;cdxxl:cdO0xl:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMWXxc;;;;;;;;;;;;;;:ldxo:;;;;;;coxxl:cdO00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMWKo:;;;;;;;;;;;;;;;;clc:;;;;;;;:odoc;:d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWXOxdx0NWWNXXKK0KKXXNWMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMWX0dc;;;;;;;;;;;;;;;;;;;:;;;;;;;;;;:loc;;cxXWMMMMMMMMMMMMMMMMMMMMMMWK0XWWN0xl:;lkOkxdolc::::cclodxOKNWMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMWNKOdl:;;;;;;;;;;;;;;;:::cc:::;;;;;;:c:;;:::;;:oKWMMMMMMMMMMMMMMMMMMMN0dokXKkoc;;;;;::;;;;;;;;;;;;;;;;:coxOXWWMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMWX0xoc:;;;;;;;;;;;;;:loxxxxdollc:;;;;;;cxOxc;;;;;;:oKWMMMMMMMMMMMMMMMMN0d:;cooc::ccllllc::;;;;;;;;;;;;;;;;;;;:ld0NWMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMN0xolc::;;;;;;;;;;;cok0XKOdlc:;;;;;;;;;;;;lkX0d:;;;;;:xNMMMMMMMMMMMMMMWKdc;;;:codxddollc:::;;;;;;;;;;;;;:ccloddxxxx0NMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMNXKXXXK0kl:;;;;;;;:okKXWNX0ko:;;;;;;;;;;;;;:oxdc;;;;;;dNMMMMMMMMMMMMMNOl::coxkkxdlc:;:lodxxxxxdoc:::coxO0KXNWWWWWWWWWMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMN0KKd:;;;;;:clxOXWWXOdc:;;;;::ccclllllcc:;;;;;;;cxKWWWNXNMMMMWXxccokOOxoc:;;cokKXNWWWMWWWNX0O0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMN0dcxXOc;;:ldk000KNNOl:;;;;;:cloxOKXNNNNXKkc;;;;;;;:oO0OodKWMMWXxlx00koc:;;;cxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMWKxc;ckNkcldO0OkoldKKxlllllcc:;;::cxNWNXWMMWOc;;;;;;;;:::::dNMMMNOkK0xl:;;;;:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMWNkl:;;l0XOO0Oxl:;;cOWX0OOkkO00Odc;;l0WWOd0NWNOddoolc:;;;;;;l0WMMMNX0dc;;;;;:lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMWKd:;;;;oKNKko:;;;;:o00xoc::cdKWWNOc;dXWWKocoxkOOO0KXKkl;;;:lOWMMMW0dc;;;;;;:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMNOl:;;;;:dOdc:;;;;;;:cl:;;;:lONWMMMNd:cox0NKxl:;::::lxXNkc:ok0WMMWXxc;;;;;;;ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMNkc;;;;;;;::;;;;;;;;;;;;;;;cxXWMMMMMXd:;;l0WWWXOo:;;;;:xNKkONWWMMNOl:;;;;;;;lOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMNx:;:;;;;;;;;;;;;;;;;;;;;;;ckNWMMMMMNkc;;;cx0KNMWNOl;;;;l0NWWMWMWNkc;;;;;;;;o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMNkloxl:;;;;;;;;;;;;;;;;;;;;lONMMMMMMN0dol:;;:lkXMMMNkc;;;:ldkkkkOO00Oxl:;;;:oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMX0KXOc;;;;;;;;;;;;;;;;;;;;cOWMMMMMMMWNXkl:cokKWMMMMW0l;;;;;;;;;;;::ldO0koc:oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMWMWKo;;;;;;;;;;;;;;;;;;;;:dNMMMMMMMMMNKkk0XNWMMMMMMMNd:;;;;;;;;;;;;;;:ok00OKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMNk:;;;;;;;;;;;;;;;;;;;;l0WMMMMMMMMMMWMMMMMMMMMMMMMWKd:;;;;;;;;;;;;;;;:lx0NWMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMXd;;;;;;;;;;;;;;;;;;;;;dXMMMMMMMMMMMMMMMMMMMMMMMMMMWNOo:;;;;;;;;;;;;;;;;coOXWMMMMMMMMMMMMWKOXWMMMMWNK0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMW0l;;;;;;;;;;;;;;;;;;;;:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0dc:;;;;;;;;;;;;;;;:lxKNWMMMMMMMMMWk:l0WMMMWNKkocloxOKNWMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMW0c;;;;;;;;;;;;;;;;;;;;:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOOOxl:;;;;;;;;;;;;;;;;cdOXWMMMMMWNOl;;l0WMMMMMWKd:;;:cokXWMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMW0c;;;;;;;;;;;;;;;;;;;;;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMW0o::ok0Oxdc;;;;;;;;;;;;;;;:lxOKXXKOdc;;;:dXMMMMMMMXd:;;;;:lkXMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMWKl;;;;;;;;;;;;;;;;;;;;;:xNMMMMMMMMMMMMMMMMMMMMMMMMWXkc;;;;:lxkOOxl:;;;;;;;;;;;;;;;::cc::;;;;;;oKWMMMMMMWk:;;;;;;:dKWMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMXd;;;;;;;;;;;;;;;;;;;;;;cONMMMMMMMMMMMMMMMMMMMMMMNOo:;;;;;;;;:cok0ko:;;;;;;;;;;;;;;;;;;;;;;;;;oXWMMMMMWXd:;;;;;;;:dXWMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMWk:;;;;;;;;;;;;;;;;;;;;;;cxXWMMMMMMMMMMMMMMMMMWNOo:;;;;;;;;;;;;;:dKXOl;;;;;;;;;;;;;;;;;;;;;;;cOWMMMMMWKd:;;;;;;;;;:kNMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMWKl;;;;;;;;;;;;;;;;;;;;;;;:oOXWMMMMMMMMMMMMWNKkl:;;;;;;;;;;;;;;;cxNMWOc;;;;;;;;;;;;;;;;;;;;:lONWWNXKkdc;;;;;;;;;;;;dXMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMNk:;;;;;;;;;;;;;;;;;;;;;;;;:lxOKNWWWWWWNX0xoc:;;;;;;;;;;;;;;;;ckNWMMXd;;;;;;;;;;;;;;;;;;;;:lddddol::;;;;;;;;;;;;;:dXMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMXd:;;;;;;;;;;;;;;;;;;;;;;;;;;:cloddddolc:;;;;;;;;;;;;;;;;;::lONMMMMNd;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;cOWMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMWKo:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:dOKWMMMMMXd;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:xNWMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMWKo:;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lkNWWMMMMMMXo;;;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ckXWMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMWKd:cdo:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;cxKWMMMMMMMMWXo;;;;;:dxc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cdKWMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMWNOdOXkl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cdKNMMMMMMMMMMMNx:;;;:dXXd:;;;;;;;;;;;;;;;;;;;;;;;;;:cokKWMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMWNNWWXko:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lxKWMMMMMMMMMMMMMWKo:;;cOWWKo:;;;;;;;;;;;;;;;:clllodxk0XWMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMWN0xl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;::ld0XWMMMMMMMMMMMMMMMMWKd:;:kWMWKo:;;;;;;;;;;;;;;:cdk0KNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMWWNKkdlc:;;;;;;;;;;;;;;;;;;;::ldk0XWMMMMMMMMMMMMMMMMMMMMWNOocoKWMWXkc:;;;;;;;;;;;;;;;:cloddxkXWMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkdollccc:::ccllodxkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMWNKO0WMMMWKko::;;;;;;;;;;;;;;;:ldOXWMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXKKKKKXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMWNKkdolcc::::ccldxOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0OOkOO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	
	]
	// var colorArr = (dndlogo)
	// for(x=0;x<6;x++)
	// document.write(dndlogo[x]+"<br/>");

	// ns.print(dndlogo)
	let printnames = dndlogo.map(s => s.split("-") || s[0])

	// let printnames = dndlogo.map(s => s.split("-")[1] || s[0]).map(s => s[0]).join("")
	ns.tprint(printnames)
}
