/** @param {NS} ns */
export async function main(ns) {

	const dndlogo = [
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0OOkkkOO0KXNWWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlc:;;;;;;;;:cox0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxl:;;;;;;;;;;;;;;;;:oONWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMWOdk0XXNWWWWWWWMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l;;;;;;;:ldxxdo:;;;;;;:xXWWKdxOKXNNWWWWWWWMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMWKo;;:clooddddddddddddddddddxxxxkkO0KNWWWMMMMMMMMMMMWKl;;;;;;:o0NWWWWWKo;;;;;;:kWWNx;;:clloddddddddddddddddddddxxxkO0KXNWWWMMMMMMMMMMMMMMMMM",
	"MMMMWKo;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:coxOKNWMMMMMMMMNx;::;;;;c0WMMMWWWWKl;;;;;;lXMWXx:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:codk0NWMMMMMMMMMMMMMMM",
	"MMMMMMNkc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;coxKWWMMMMWXo;okl;;;dKXNMWNWWWXo;;;;;;lKWMWNOl;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lx0NWMMMMMMMMMMMM",
	"MMMMMMMWKxl:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:o0NWMMWNdcONOc;cO0oOW0k0XW0c;;;;;;oXWMMMWNko:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lkXWMMMMMMMMMM",
	"MMMMMMMMWWXOl;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:o0WWWWOkX0OOooKk:lOkc:dXOc;;;;;:OWMMMMMMWN0o:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lONWMMMMMMMM",
	"MMMMMMMMMMMW0c;;;;;;;;;;;;::::::::;;;;;;;;;;;;;;;;;ckNWWXXNxcdOKNk:;:oolloO0dc;;:xNWMMMMMMMMWXo;;;;;;;;;;;;;::::::::;;;;;;;;;;;;;;;;:dKWMMMMMMM",
	"MMMMMMMMMMMWKl;;;;;;;;;;;:xKKKKKK0Okxl:;;;;;;;;;:;;;:xXN0xdo:;:ldxdl;;ccloldkOxlkNMMMMMMMMMMMNx:lllodxkkkxdx0KKKKK00Oxo:;;;;;;;;;;;;;;o0WMMMMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:OWMMMMMMMMWN0d:;;;;;;;;;;;;:xNNOc;;;;;;;clc:;;;:lllokKNWMMMMMMMMMMMWK0XKO0XNWNNX0KWWWMMMMMMWNKxc;;;;;;;;;;;;;oKMMMMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:OWMMMMMMMMWWWNOl;;;;;;;;;:cdkK0dc;;;;;;;;;::;;;;;:cc:oKWMMMMMMMMMWXKXKkl:lxdollllodk0NWMMMMMMWWKo;;;;;;;;;;;;;dNMMMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:OWMMMMMMMMMMMMWOc;;;;;;:dkOkoc:;;;;;codolc::;;;;col:;;lKWMMMMMMWXxcldoccc:;;;;;;;;;;:lxKWMMMMMMWKo;;;;;;;;;;;;c0WMMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:OWMMMMMMMMMMMMWNd;;;;:d0NX0kkdc;;;;ckXXkc;;;;;;;;loc;;;xNMMMMMNOlcloolllodddolccoxkO0KKXWMMMMMMMWk:;;;;;;;;;;;:xNMMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:OWMMMMMMMMMMMMWWk:;;cdxxx0XKOKk:;ldkKKkl:;;clodkkkxl;;;cxO0NWNkdddoc:lkOOkxxkOOOk0WMMMMMMMMMMMMWW0c;;;;;;;;;;;;dXMMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:OWMMMMMMMMMMMWWWO:;;;;;ck0x:oKOxOOkKN0xxxdl:lx0XKXXxll:;;:xNWXOdc;;lOOdc;;;;,:lc;dNMMMMMMMMMMMMMWKl;;;;;;;;;;;;oXWMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:OWMMMMMMMMMMMMMNx:;;;;lOOl;;xNXko:cOKkdkXWXocdkKkodddkkl:dXWKxc;;:dKOc;;;;;;;;;;;xNMMMMMMMMMMMMMW0c;;;;;;;;;;;;dNMMMM",
	"MMMMMMMMMMMMXl;;;;;;;;;;;:OWMMMMMMMMMMMMWKl;;;;c0Oc;;:xOo:;;clc:oKWWNx;,cOX0dc;:k00NW0l;;;:kNNd;;;;;;;;;;;;xNMMMMMMMMMMMMMNx;;;;;;;;;;;;:OWMMMM",
	"MMMMMMMMMMMMXl;;;;;;;;;;;:OWMMMMMMMMMWMWXd:;;;:xKkl:;:c:;;;;;;:dXWMWKd:;:oKWWk:;cdxkOOkdccONMNxcc:;;;;;;;;;xNMMMMMMMMMMMWWOc;;;;;;;;;;;;oXWMMMM",
	"MMMMMMMMMMMMXl;;;;;;;;;;;:OWMMMMMMMMWWWKd:;;;;cONXk:;;;;;;;;;;oXWMMMN0OO0XWMMXo;;;;;;cok0KNWMNdcO0xoc:ccc::xNMMMMMMWMMWWXxc;;;;;;;;;;;;cOWMMMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:OWWMWWWWWNKOdc;;;;;;lKWXo;;;;;;;;;;:OWMMMMMMMWMMMMMWKd:;;;;;;:lxKWWNd;oXX00KXKOkkKWWMWWWWWNX0xl;;;;;;;;;;;;;:kNWMMMMM",
	"MMMMMMMMMMMWXl;;;;;;;;;;;:ldddddddol:;;;;;;;;;lkXOc;;;;;;;;;;:OWMMMMMMWWMMMMMMWN0xl;;;;;;;cd0XOokKxckNX0Odlox0NKxddolc:;;;;;;;;;;;;;;ckNMMMMMMM",
	"MMMMMMMMMMMWKl;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;l0k:;;;;;;;;;;:kWMMMMMMMMMMMMWWKdokOko:;;;;;;:ldxxl:;lKkckKo;;:d0kc;;;;;;;;;;;;;;;;;;l0WMMMMMMMM",
	"MMMMMMMMMMMWKl;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;c0O:;;;;;;;;;;;cOWWWMMMMMMMWWXkc;;;cdOOo:;;;;;;;;;;;;lK0dO0l;;;;oKx:;;;;;;;;;;;;;;;lkXWMMMMMMMMM",
	"MMMMMMMMMMWNOc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lxXKl;;;;;;;;;;;;cd0NWMMWWWN0xl;;;;;;;oKNx:;;;;;;;;;;cxKOkdc;;;;;cOOc;;;;;;;;;;;;cdONWMMMMMMMMMMM",
	"MMMMMMMWWXOdc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;cox0XWWNk:;;;;;;;;;;;;;:ldxxxddl:;;;;;;;;l0WWO:;;;;;;;;;;::::;;;;;;;;l0k:;;;;;;;;:ldOXWMMMMMMMMMMMMMM",
	"MMMMMWXOdl::::::::::::::::::::::::cclloxkOKNMMMMMMNx:;::;;;;;;;;;;;;;;;;;;;;;;;;;:dKWMWO:;;::;;;;;;;;;;;;;;;;;lO0o::cclodxOKNWMMMMMMMMMMMMMMMMM",
	"MMMMMWXK0KKKKKKKKKKKKKKKKKKKKKKKKKXXNWWWMMWMMMMMMMMNkdOxc;;;;;;;;;;;;;;;;;;;;;;:o0NWMMM0c;:xd:;;;;;;;;;;;;;cokXWNKKKXXNWWWWMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWKxl;;;;;;;;;;;;;;;;;:cd0NWMMMMMNx:c0Kd:;;;;;;;:ldxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xolc:;;;;::ccldx0XWWMMMMMMMMN0x0NNkl:;;;;;;:clx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK00000KKXNWWMMMMMMMMMMMMMMWWWMWN0xdoooodxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	]
	// var colorArr = (dndlogo)
	// for(x=0;x<6;x++)
	// document.write(dndlogo[x]+"<br/>");

	// ns.print(dndlogo)
	let printnames = dndlogo.map(s => s.split("-") || s[0])
	// modified version of the code below
	// let printnames = dndlogo.map(s => s.split("-")[1] || s[0]).map(s => s[0]).join("")
	ns.tprint(printnames)
}
